// A Dart port of Yomitan's LanguageTransformer
// (ext/js/language/language-transformer.js), driving its Japanese rule set
// (japanese_transforms.g.dart, generated by tools/gen-japanese-transforms.mjs).
// Yomitan is GPL-3.0, as is this app.

part 'japanese_transforms.g.dart';

/// One candidate dictionary form of a looked-up word.
class JapaneseDeinflection {
  /// Create a candidate.
  const JapaneseDeinflection({
    required this.text,
    required this.conditions,
    required this.transforms,
  });

  /// The candidate form, e.g. 食べる for 食べさせられた.
  final String text;

  /// Condition flags of [text]; 0 for the unchanged source text.
  final int conditions;

  /// Ids of the transforms undone to get here, outermost first.
  final List<String> transforms;
}

class _Rule {
  const _Rule(
    this.type,
    this.inflected,
    this.deinflected,
    this.conditionsIn,
    this.conditionsOut,
  );

  final String type;
  final String inflected;
  final String deinflected;
  final int conditionsIn;
  final int conditionsOut;

  bool isInflected(String text) => switch (type) {
    's' => text.endsWith(inflected),
    'p' => text.startsWith(inflected),
    _ => text == inflected,
  };

  String deinflect(String text) => switch (type) {
    's' => text.substring(0, text.length - inflected.length) + deinflected,
    'p' => deinflected + text.substring(inflected.length),
    _ => deinflected,
  };
}

class _Transform {
  const _Transform(this.id, this.rules);

  final String id;
  final List<_Rule> rules;
}

/// Japanese deinflection the way current Yomitan does it: every rule whose
/// input conditions fit is undone in turn (breadth first), each step
/// narrowing the conditions, until no rule applies.
class JapaneseTransformer {
  JapaneseTransformer._() {
    _buildFlags();
    for (final entry in _jaTransforms.entries) {
      _transforms.add(
        _Transform(entry.key, [
          for (final (type, inflected, deinflected, conditionsIn, conditionsOut)
              in entry.value)
            _Rule(
              type,
              inflected,
              deinflected,
              _flagsOf(conditionsIn),
              _flagsOf(conditionsOut),
            ),
        ]),
      );
    }
  }

  /// The shared instance; the rules are built once.
  static final JapaneseTransformer instance = JapaneseTransformer._();

  final Map<String, int> _flags = {};
  final List<_Transform> _transforms = [];
  int _dictionaryFormFlags = 0;

  /// Mirrors Yomitan's _getConditionFlagsMap: each leaf condition gets
  /// its own bit, and a condition with sub-conditions is the union of
  /// theirs.
  void _buildFlags() {
    int next = 0;
    var targets = _jaConditions.entries.toList();
    while (targets.isNotEmpty) {
      final retry = <MapEntry<String, (bool, List<String>)>>[];
      for (final target in targets) {
        final subConditions = target.value.$2;
        if (subConditions.isEmpty) {
          _flags[target.key] = 1 << next++;
        } else if (subConditions.every(_flags.containsKey)) {
          _flags[target.key] = _flagsOf(subConditions);
        } else {
          retry.add(target);
        }
      }
      if (retry.length == targets.length) {
        throw StateError('Cycle in Japanese transform conditions');
      }
      targets = retry;
    }
    for (final entry in _jaConditions.entries) {
      if (entry.value.$1) _dictionaryFormFlags |= _flags[entry.key]!;
    }
  }

  int _flagsOf(List<String> conditions) =>
      conditions.fold(0, (flags, c) => flags | (_flags[c] ?? 0));

  static bool _conditionsMatch(int current, int next) =>
      current == 0 || (current & next) != 0;

  /// Every form [source] may be an inflection of, including [source]
  /// itself (first, with conditions 0). A port of Yomitan's
  /// LanguageTransformer.transform.
  List<JapaneseDeinflection> transform(String source) {
    final results = <JapaneseDeinflection>[
      JapaneseDeinflection(text: source, conditions: 0, transforms: const []),
    ];
    // (transform id, rule index, text) already undone on each result's
    // path, to stop cycles.
    final traces = <List<(String, int, String)>>[const []];

    for (int i = 0; i < results.length; i++) {
      final current = results[i];
      for (final transform in _transforms) {
        for (int j = 0; j < transform.rules.length; j++) {
          final rule = transform.rules[j];
          if (!_conditionsMatch(current.conditions, rule.conditionsIn)) {
            continue;
          }
          if (!rule.isInflected(current.text)) continue;
          final frame = (transform.id, j, current.text);
          if (traces[i].contains(frame)) continue;

          results.add(
            JapaneseDeinflection(
              text: rule.deinflect(current.text),
              conditions: rule.conditionsOut,
              transforms: [transform.id, ...current.transforms],
            ),
          );
          traces.add([frame, ...traces[i]]);
        }
      }
    }
    return results;
  }

  /// The distinct candidate dictionary forms of [source], excluding
  /// [source] itself: those whose conditions include a dictionary form
  /// (v1, v5, adj-i, …). Intermediate stems such as a bare -ます stem are
  /// dropped, as only a dictionary form can be a headword. (Yomitan also
  /// checks each candidate against the matched entry's part of speech;
  /// entries here do not store it, so that last check is skipped.)
  List<String> dictionaryForms(String source) {
    final forms = <String>[];
    for (final result in transform(source)) {
      if (result.conditions == 0) continue;
      if (result.conditions & _dictionaryFormFlags == 0) continue;
      if (result.text.isEmpty || result.text == source) continue;
      if (!forms.contains(result.text)) forms.add(result.text);
    }
    return forms;
  }
}
